### ISSUE TITLE
pass environment var from command line options

### ISSUE THREAD

**Issue by missedone** [grammarly/rocker-compose#15]
hi folks

i have env var defined in the yaml spec:
```yaml
namespace: nick
containers:
  web:
    image: web:latest
    env:
      DB_HOST: 192.168.59.104
      DB_PORT: 5432
      DB_NAME: testdb
    ports:
      - "8080:8080"
```

but when dev/test, i'd like to pass the DB_* env from command line to easy switch different env, but i found it's not doable with current version of rocker-compose.
i tried `DB_HOST=XXXX rocker-compose run ...`, or `rocker-compose run ... --var DB_HOST=xxxx`, neither of them works
