### ISSUE TITLE
Watch mounted volume?

### ISSUE THREAD

**Issue by ericclemmons** [grammarly/rocker-compose#17]
First off, **thank you** for making something so easy & approachable!

We've avoided Docker because of the headache in setup, but I was able to:

1. Install Docker Toolbox.
2. Install `rocker-compose`.
3. Actually get my Node app running with a single `compose.yml`!

Is there a way to watch for changes?  I didn't see anything with `rocker-compose`, so if I need to look elsewhere please let me know :)

```yml
namespace: forms
containers:
  app:
    cmd: |-
      cd /var/www
      npm install
      NODE_ENV=staging npm run dev
    image: node:4.1.1
    links:
      - redis:redis
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - .:/var/www

  redis:
    image: redis:3.0.4
    volumes_from:
      - redis_data

  redis_data:
    image: grammarly/scratch:latest
    state: created
    volumes:
      - /data
```
