### ISSUE TITLE
Failed to start all defined containers

### ISSUE THREAD

**Issue by ghost** [grammarly/rocker-compose#21]
When I want to start this test environment via
rocker-compose run -f dev.yml -force localhost:5000/ubuntu-apache:latest
It only starts the mysql container (actually called dbtest_mysql) under the wrong name apache-test, while the actual container apache-test stays in state restarting. I think that's the case because it gives the wrong name to the mysql container and then tries to start the actual container with the same name, which fails all the time.

Contents of dev.yml:
namespace: test # specify a manifest-level namespace under which all containers will be named
containers:
  apache-test: # container name will be "wordpress.main"
    image: localhost:5000/ubuntu-apache
    hostname: apache-test
    domainname: apache-test.dockerhost.example.com
    env:
      VIRTUAL_HOST: apache-test.dockerhost.example.com
    expose:
      - "80"
      - "443"
    volumes:
      - /etc/certs:/etc/apache2/certs
      - /var/cache/rocker-compose/config/apache/apache-test:/etc/apache2/sites-enabled
      - /var/cache/rocker-compose/repos/apache-test:/var/www/html
      - /var/cache/rocker-compose/config/scripts/apache-test:/usr/local/bin
    entrypoint: /usr/local/bin/startup.sh
    links:
       - dbtest_mysql:mysql

   dbtest_mysql:
     image: mysql:5.6
     state: running
     env:
       MYSQL_ROOT_PASSWORD: supersecurerootpw # provide MYSQL_ROOT_PASSWORD env var
     volumes_from:
       # specify to mount all volumes from "db_data" container, this way we can
       # update "db" container without loosing data
       - dbtest_data

   dbtest_data:
     image: grammarly/scratch:latest # use empty image, just for data
     state: created # this tells compose to not try to run this container, data containers need to be only created
     volumes:
       # define the empty directory that will be used by the "db" container
       - /var/cache/rocker-compose/data/mysql/apache-test-test

**Comment by ybogdanov** [comment]
Hi @ManuelStoessel,

Can you please post a formatted version of your `compose.yml` once again so I can see it better?
You can use [github flavored markdown](https://help.github.com/articles/github-flavored-markdown/) capabilities to highlight YAML syntax like this:

    ```yaml
    your yaml here
    ```

**Comment by ManuelStoessel** [comment]
Hi @ybogdanov,
sure :-) here you go
```yaml
namespace: test # specify a manifest-level namespace under which all containers will be named
containers:
apache-test: # container name will be "wordpress.main"
image: localhost:5000/ubuntu-apache
hostname: apache-test
domainname: apache-test.dockerhost.example.com
env:
VIRTUAL_HOST: apache-test.dockerhost.example.com
expose:
- "80"
- "443"
volumes:
- /etc/certs:/etc/apache2/certs
- /var/cache/rocker-compose/config/apache/apache-test:/etc/apache2/sites-enabled
- /var/cache/rocker-compose/repos/apache-test:/var/www/html
- /var/cache/rocker-compose/config/scripts/apache-test:/usr/local/bin
entrypoint: /usr/local/bin/startup.sh
links:
- dbtest_mysql:mysql

dbtest_mysql:
image: mysql:5.6
state: running
env:
MYSQL_ROOT_PASSWORD: supersecurerootpw # provide MYSQL_ROOT_PASSWORD env var
volumes_from:
# specify to mount all volumes from "db_data" container, this way we can
# update "db" container without loosing data
- dbtest_data

dbtest_data:
image: grammarly/scratch:latest # use empty image, just for data
state: created # this tells compose to not try to run this container, data containers need to be only created
volumes:
# define the empty directory that will be used by the "db" container
- /var/cache/rocker-compose/data/mysql/apache-test-test
```
