### ISSUE TITLE
Array passing

### ISSUE THREAD

**Issue by mancvso** [grammarly/rocker-compose#24]
Currently we are trying to "link" more than one instance of a specific service (like mongodb) to a container defined in a YAML file similar to this one

```
namespace: {{ .namespace }}
containers:
  _box:
    image: {{ .image }}:{{ .imagetag }}
    expose: {{ or .expose "8080" }}
    env:
      VIRTUAL_HOST: {{ .VIRTUAL_HOST }}
      PORT: {{ or .PORT "8080" }}
    volumes_from: data
    links:
{{ range $link := .links }}
      -{{ $link.external }}:{{ $link.internal }}
{{ end }}

  data:
    image: some/image:latest
    state: created
    cmd: true
    volume:
      - /usr/data/app

  {{ range $n := seq .n }}
  box_{{$n}}:
    extends: _box
    cmd: some_command
  {{ end }}
```

But we cannot manage to make rocker-compose recognize the array of objects (in this case, the links).
Those containers are started separately from this composition.

Does rocker-compose supports the passing of arrays?
