### ISSUE TITLE
Semver matching for image names

### ISSUE THREAD

**Issue by ybogdanov** [grammarly/rocker-compose#31]
```
namespace: example
  containers:
    main1:
       image: ubuntu:14.04.*
       cmd: ["/bin/sh", "-c", "echo hello1"]

     main2:
       image: ubuntu:~14
       cmd: ["/bin/sh", "-c", "echo hello2"]
```

Is a rewrite of https://github.com/grammarly/rocker-compose/pull/5
