### ISSUE TITLE
rocker-compose remove volumes if dependant container re-creates, Docker 1.9

### ISSUE THREAD

**Issue by valch85** [grammarly/rocker-compose#35]

**Comment by ybogdanov** [comment]
Same problem as https://github.com/grammarly/rocker/issues/51

```
containers:
  a:
    volumes: /data
  b:
    volumes_from: a
```

When `b` changes, rocker-compose will remove and create the container. While removing `b`, Docker 1.9 removes the `/data` volume of `a`.
