### ISSUE TITLE
Unable to use network name as "net" parameter

### ISSUE THREAD

**Issue by vlfesko** [grammarly/rocker-compose#36]
Hello,
Since docker 1.9+ does not add host entries to /etc/hosts for all containers connected to default bridge the solution was to create new bridge and attach containers to it like that:

    $ docker network create -d bridge localnet

Then I start containers:

    $ docker run --rm --net localnet -h u1 --name u1 -ti ubuntu:14.04
    $ docker run --rm --net localnet -h u1 --name u1 -ti ubuntu:14.04

As a result both containers have /etc/hosts entries for each other and it works just fine. But when converted to rocker-compose this setup does not work, compose.yml:
```
namespace: test
containers:
  u1:
    image: ubuntu:14.04
    container_name: u1
    hostname: u1
    net: localnet

  u2:
    image: ubuntu:14.04
    container_name: u2
    hostname: u2
    net: localnet
```

```
$ rocker-compose run
INFO[0000] Reading manifest: compose.yml
FATA[0000] Failed to parse YAML config, error: Unknown net type: localnet
```

At the same time docker-compose handles this setup without problems.
Is this an issue or it is another way in RC to handle setup like this?

Thx!

**Comment by ybogdanov** [comment]
Hi @vlfesko,
Yeah, we have to add support for that. Also, I have plans to allow create networks right from RC, like this:
```yaml
namespace: myapp
networks:
  - driver: bridge
    name: localnet
containers:
  ...
```

Will do it soon!
