### ISSUE TITLE
Use named volumes

### ISSUE THREAD

**Issue by alkersan** [grammarly/rocker-compose#38]
Similar to networks in #36 docker 1.9 added [volume management API](https://docs.docker.com/engine/reference/commandline/volume_create/). Now it's possible to create and mount named volumes:

```
docker volume create --name mysql-data
docker run -d -v mysql-data:/var/lib/mysql mysql:5.6
```

Would be useful to have similar syntax in `compose.yml`:

``` yaml
db:
    image: mysql:5.6
    volumes:
      - mysql-data:/var/lib/mysql
```
